// This file is auto-generated by @hey-api/openapi-ts

export type Author = {
  id: number;
  name: string;
};

export type AuthorCreate = {
  name: string;
};

export type Book = {
  id: number;
  title: string;
  author: number;
  genre?: number | null;
  published_date?: string | null;
  description?: string | null;
  image?: string | null;
  pdf_url: string;
};

export type CreateBook = {
  title: string;
  author: string;
  genre?: string | null;
  published_date?: string | null;
  description?: string | null;
  image?: string | null;
  pdf_url: string;
};

export type Genre = {
  id: number;
  name: string;
};

export type GenreCreate = {
  name: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type UserLogin = {
  /**
   * Электронная почта
   */
  email: string;
  /**
   * Пароль, от 5 до 50 знаков
   */
  password: string;
};

export type UserRegister = {
  /**
   * Электронная почта
   */
  email: string;
  /**
   * Пароль, от 5 до 50 знаков
   */
  password: string;
  /**
   * Имя, от 3 до 50 символов
   */
  name: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetBooksBooksGetData = {
  query?: {
    /**
     * Filter by author
     */
    author?: string | null;
    /**
     * Filter by description keyword
     */
    description?: string | null;
    /**
     * Filter by name
     */
    genre?: string | null;
    /**
     * Filter by book ID
     */
    id?: number | null;
    /**
     * Filter by PDF URL
     */
    pdf_url?: string | null;
    /**
     * Filter by publication date
     */
    published_date?: string | null;
    /**
     * Filter by book title
     */
    title?: string | null;
  };
};

export type GetBooksBooksGetResponse = Array<Book>;

export type GetBooksBooksGetError = HTTPValidationError;

export type GetBookBooksIdGetData = {
  path: {
    id: number;
  };
};

export type GetBookBooksIdGetResponse = Book;

export type GetBookBooksIdGetError = HTTPValidationError;

export type CreateBookBooksCreatePostData = {
  body: CreateBook;
};

export type CreateBookBooksCreatePostResponse = number;

export type CreateBookBooksCreatePostError = HTTPValidationError;

export type UpdateBookBooksIdUpdatePutData = {
  body: CreateBook;
  path: {
    id: number;
  };
};

export type UpdateBookBooksIdUpdatePutResponse = Book;

export type UpdateBookBooksIdUpdatePutError = HTTPValidationError;

export type DeleteBookBooksIdDeleteDeleteData = {
  path: {
    id: number;
  };
};

export type DeleteBookBooksIdDeleteDeleteResponse = Book;

export type DeleteBookBooksIdDeleteDeleteError = HTTPValidationError;

export type GetProfileUsersProfileGetResponse = unknown;

export type GetProfileUsersProfileGetError = unknown;

export type LoginUsersLoginPostData = {
  body: UserLogin;
};

export type LoginUsersLoginPostResponse = unknown;

export type LoginUsersLoginPostError = HTTPValidationError;

export type RegisterUsersRegisterPostData = {
  body: UserRegister;
};

export type RegisterUsersRegisterPostResponse = unknown;

export type RegisterUsersRegisterPostError = HTTPValidationError;

export type LogoutUserUsersLogoutPostResponse = unknown;

export type LogoutUserUsersLogoutPostError = unknown;

export type GetAuthorsAuthorsGetData = {
  query?: {
    /**
     * Filter by author id
     */
    id?: number | null;
    /**
     * Find by author name
     */
    name?: string | null;
  };
};

export type GetAuthorsAuthorsGetResponse = Array<Author>;

export type GetAuthorsAuthorsGetError = HTTPValidationError;

export type CreateAuthorAuthorsCreatePostData = {
  body: AuthorCreate;
};

export type CreateAuthorAuthorsCreatePostResponse = number;

export type CreateAuthorAuthorsCreatePostError = HTTPValidationError;

export type DeleteAuthorAuthorsDeleteDeleteData = {
  query: {
    id: number;
  };
};

export type DeleteAuthorAuthorsDeleteDeleteResponse = Author;

export type DeleteAuthorAuthorsDeleteDeleteError = HTTPValidationError;

export type DeleteAuthorAuthorsUpdateIdPutData = {
  body: AuthorCreate;
  path: {
    id: number;
  };
};

export type DeleteAuthorAuthorsUpdateIdPutResponse = Author;

export type DeleteAuthorAuthorsUpdateIdPutError = HTTPValidationError;

export type GetGenresGenresGetData = {
  query?: {
    /**
     * Filter by genre id
     */
    id?: number | null;
    /**
     * Find by genre name
     */
    name?: string | null;
  };
};

export type GetGenresGenresGetResponse = Array<Genre>;

export type GetGenresGenresGetError = HTTPValidationError;

export type CreateGenreGenresCreatePostData = {
  body: GenreCreate;
};

export type CreateGenreGenresCreatePostResponse = number;

export type CreateGenreGenresCreatePostError = HTTPValidationError;

export type DeleteGenreGenresDeleteDeleteData = {
  query: {
    id: number;
  };
};

export type DeleteGenreGenresDeleteDeleteResponse = Genre;

export type DeleteGenreGenresDeleteDeleteError = HTTPValidationError;

export type DeleteGenreGenresUpdateIdPutData = {
  body: GenreCreate;
  path: {
    id: number;
  };
};

export type DeleteGenreGenresUpdateIdPutResponse = Genre;

export type DeleteGenreGenresUpdateIdPutError = HTTPValidationError;
