// This file is auto-generated by @hey-api/openapi-ts

export type Author = {
  id: number;
  name: string;
};

export type AuthorCreate = {
  name: string;
};

export type Body_upload_file_storage_upload__post = {
  file: Blob | File;
};

export type Book = {
  id: number;
  title: string;
  author: number;
  genre?: number | null;
  publishedDate?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  pdfUrl: string;
};

export type CreateBook = {
  title: string;
  author: string;
  genre?: string | null;
  publishedDate?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  pdfUrl: string;
};

export type FileUploadedScheme = {
  url: string;
};

export type Genre = {
  id: number;
  name: string;
};

export type GenreCreate = {
  name: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type UserLogin = {
  /**
   * Электронная почта
   */
  email: string;
  /**
   * Пароль, от 5 до 50 знаков
   */
  password: string;
};

export type UserLogined = {
  /**
   * Электронная почта
   */
  email: string;
  /**
   * Имя, от 3 до 50 символов
   */
  name: string;
  privileges: string;
};

export type UserRegister = {
  /**
   * Электронная почта
   */
  email: string;
  /**
   * Пароль, от 5 до 50 знаков
   */
  password: string;
  /**
   * Имя, от 3 до 50 символов
   */
  name: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetBooksBooksGetData = {
  query?: {
    /**
     * Filter by author
     */
    author?: string | null;
    /**
     * Filter by description keyword
     */
    description?: string | null;
    /**
     * Filter by name
     */
    genre?: string | null;
    /**
     * Filter by image's URL
     */
    image_url?: string | null;
    /**
     * Filter by PDF URL
     */
    pdf_url?: string | null;
    /**
     * Filter by publication date
     */
    published_date?: string | null;
    /**
     * Filter by book title
     */
    title?: string | null;
  };
};

export type GetBooksBooksGetResponse = Array<Book>;

export type GetBooksBooksGetError = HTTPValidationError;

export type GetBookBooksBookIdGetData = {
  path: {
    book_id: number;
  };
};

export type GetBookBooksBookIdGetResponse = Book;

export type GetBookBooksBookIdGetError = HTTPValidationError;

export type CreateBookBooksCreatePostData = {
  body: CreateBook;
};

export type CreateBookBooksCreatePostResponse = number;

export type CreateBookBooksCreatePostError = HTTPValidationError;

export type UpdateBookBooksBookIdUpdatePutData = {
  body: CreateBook;
  path: {
    book_id: number;
  };
};

export type UpdateBookBooksBookIdUpdatePutResponse = Book;

export type UpdateBookBooksBookIdUpdatePutError = HTTPValidationError;

export type DeleteBookBooksBookIdDeleteDeleteData = {
  path: {
    book_id: number;
  };
};

export type DeleteBookBooksBookIdDeleteDeleteResponse = Book;

export type DeleteBookBooksBookIdDeleteDeleteError = HTTPValidationError;

export type GetProfileUsersProfileGetResponse = UserLogined;

export type GetProfileUsersProfileGetError = unknown;

export type LoginUsersLoginPostData = {
  body: UserLogin;
};

export type LoginUsersLoginPostResponse = UserLogined;

export type LoginUsersLoginPostError = HTTPValidationError;

export type RegisterUsersRegisterPostData = {
  body: UserRegister;
};

export type RegisterUsersRegisterPostResponse = UserLogined;

export type RegisterUsersRegisterPostError = HTTPValidationError;

export type LogoutUserUsersLogoutPostResponse = unknown;

export type LogoutUserUsersLogoutPostError = unknown;

export type GetAuthorsAuthorsGetData = {
  query?: {
    /**
     * Find by author name
     */
    name?: string | null;
  };
};

export type GetAuthorsAuthorsGetResponse = Array<Author>;

export type GetAuthorsAuthorsGetError = HTTPValidationError;

export type GetAuthorAuthorsAuthorIdGetData = {
  path: {
    author_id: number;
  };
};

export type GetAuthorAuthorsAuthorIdGetResponse = Author;

export type GetAuthorAuthorsAuthorIdGetError = HTTPValidationError;

export type CreateAuthorAuthorsCreatePostData = {
  body: AuthorCreate;
};

export type CreateAuthorAuthorsCreatePostResponse = number;

export type CreateAuthorAuthorsCreatePostError = HTTPValidationError;

export type DeleteAuthorAuthorsAuthorIdDeleteDeleteData = {
  path: {
    author_id: number;
  };
};

export type DeleteAuthorAuthorsAuthorIdDeleteDeleteResponse = Author;

export type DeleteAuthorAuthorsAuthorIdDeleteDeleteError = HTTPValidationError;

export type UpdateAuthorAuthorsAuthorIdUpdatePutData = {
  body: AuthorCreate;
  path: {
    author_id: number;
  };
};

export type UpdateAuthorAuthorsAuthorIdUpdatePutResponse = Author;

export type UpdateAuthorAuthorsAuthorIdUpdatePutError = HTTPValidationError;

export type GetGenresGenresGetData = {
  query?: {
    /**
     * Find by genre name
     */
    name?: string | null;
  };
};

export type GetGenresGenresGetResponse = Array<Genre>;

export type GetGenresGenresGetError = HTTPValidationError;

export type GetGenreGenresGenreIdGetData = {
  path: {
    genre_id: number;
  };
};

export type GetGenreGenresGenreIdGetResponse = Genre;

export type GetGenreGenresGenreIdGetError = HTTPValidationError;

export type CreateGenreGenresCreatePostData = {
  body: GenreCreate;
};

export type CreateGenreGenresCreatePostResponse = number;

export type CreateGenreGenresCreatePostError = HTTPValidationError;

export type DeleteGenreGenresGenreIdDeleteDeleteData = {
  path: {
    genre_id: number;
  };
};

export type DeleteGenreGenresGenreIdDeleteDeleteResponse = Genre;

export type DeleteGenreGenresGenreIdDeleteDeleteError = HTTPValidationError;

export type UpdateGenreGenresGenreIdUpdatePutData = {
  body: GenreCreate;
  path: {
    genre_id: number;
  };
};

export type UpdateGenreGenresGenreIdUpdatePutResponse = Genre;

export type UpdateGenreGenresGenreIdUpdatePutError = HTTPValidationError;

export type UploadFileStorageUploadPostData = {
  body: Body_upload_file_storage_upload__post;
};

export type UploadFileStorageUploadPostResponse = FileUploadedScheme;

export type UploadFileStorageUploadPostError = HTTPValidationError;

export type DownloadFileStorageDownloadFileNameGetData = {
  path: {
    file_name: string;
  };
};

export type DownloadFileStorageDownloadFileNameGetResponse = unknown;

export type DownloadFileStorageDownloadFileNameGetError = HTTPValidationError;
